---
deployment:
  tasks:
    - export DEPLOYPATH=/home/a147409/api/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH

    - /bin/cp -r application $DEPLOYPATH
    - /bin/cp -r system $DEPLOYPATH
    - /bin/cp -r uploads $DEPLOYPATH
