---
deployment:
  tasks:
    - export DEPLOYPATH=/home/a147409/admin/
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp codiniterIndex.php $DEPLOYPATH

    - /bin/cp -r application $DEPLOYPATH
    - /bin/cp -r system $DEPLOYPATH
    - /bin/cp -r vendor $DEPLOYPATH


    - /bin/cp .editorconfig /home/a147409/public_html/
    - /bin/cp contributing.md /home/a147409/public_html/
    - /bin/cp codiniterIndex.php /home/a147409/public_html/

    - /bin/cp -r application /home/a147409/public_html/
    - /bin/cp -r system /home/a147409/public_html/
    - /bin/cp -r vendor /home/a147409/public_html/

